#!/bin/bash
#streamlink -p omxplayer --fifo "https://www.youtube.com/watch?v=JEPRVy1jat4" best

if [[ "$1" =~ (mp4$|mkv$|avi$) ]]
then
	sleep 5
	omxplayer --loop -b $1
	exit
else

	while :
	do
    		streamlink -p omxplayer --fifo $1 best
    		sleep 10
    		if [ -f "/tmp/youdienow" ];
    		then
	    		exit
    		fi
	done
fi
