#!/bin/bash
if [[ "$1" =~ ^http ]]
then
	while :
	do
    		/usr/local/bin/streamlink -p "omxplayer -b" --fifo $1 best
    		sleep 10
    		if [ -f "/tmp/youdienow" ];
    		then
	    		exit
    		fi
	done
else
        sleep 5
        /usr/bin/omxplayer --loop -b $1
        exit
fi
