#!/usr/bin/env python3
# This takes everything from the commandline and throws it to syslog.

import syslog
import sys
sys.argv[0]="Cleaner"
input=sys.argv
input.pop(0)
output=' '.join(input)

syslog.syslog(syslog.LOG_NOTICE, output)
