#!/usr/bin/env python3

import os
import signal
import subprocess
import random
from random import shuffle
from sys import exit, version_info
import syslog
import time
import socket
import touchphat

def kill_everything():
    syslog.syslog(syslog.LOG_NOTICE, "Killing old processes.")
    subprocess.Popen(["killall", "-9", "steamer_helper_script"])   
    subprocess.Popen(["killall", "-9", "video_helper_script"])   
    subprocess.Popen(["killall", "-9", "streamlink"])   
    subprocess.Popen(["killall", "-9", "omxplayer"])   
    subprocess.Popen(["killall", "-9", "omxplayer.bin"])   


syslog.syslog(syslog.LOG_NOTICE, "Hi there! Waiting for network to be available.")

while True:
    nointernet=10
    try:
        socket.gethostbyname("youtube.com")
    except:
        time.sleep(1)
        nointernet=1

    if (nointernet == 10):
        break

#stcmd="/home/pi/stream/streamer_helper_script"
stream_cmd="/home/pi/stream/streamer_helper_script"
video_cmd="/home/pi/stream/video_helper_script"
with open("/home/pi/stream/streams.dat") as s:
    streams=s.readlines()

shuffle(streams)
numstreams=len(streams)

msg=str(numstreams)+" streams detected."
syslog.syslog(syslog.LOG_NOTICE, msg)

s = random.randint(1,numstreams)
s=s-1
(stype,url,desc) = streams[s].split(',')
msg="Starting at stream "+str(s)+": "+desc
syslog.syslog(syslog.LOG_NOTICE, msg)

if (stype == "s"):
    subprocess.Popen([stream_cmd, url])
elif (stype == "v"):
    subprocess.Popen([video_cmd, url])

@touchphat.on_release("Enter")
def back_one():
    global s
    s=s+1
    if s == numstreams:
        s = 0
    (stype,url,desc) = streams[s].split(',')
    msg="Switching to stream "+str(s)+": "+desc
    syslog.syslog(syslog.LOG_NOTICE, msg)
    kill_everything()
    if (stype == "s"):
        subprocess.Popen([stream_cmd, url])
    elif (stype == "v"):
            subprocess.Popen([video_cmd, url])


@touchphat.on_release("Back")
def forward_one():
    global s
    s=s-1
    if s == -1:
        s = (numstreams-1)

    (stype,url,desc) = streams[s].split(',')
    msg="Switching to stream "+str(s)+": "+desc
    syslog.syslog(syslog.LOG_NOTICE, msg)

    kill_everything()
    if (stype == "s"):
        subprocess.Popen([stream_cmd, url])
    elif (stype == "v"):
            subprocess.Popen([video_cmd, url])


signal.pause()
