#!/usr/bin/env python3

import os
import signal
import subprocess
import random
from random import shuffle
from sys import exit, version_info
import syslog
import time
import socket
import touchphat

home="/home/pi/touchphat-stream/"
stream_cmd=home+"streamer_helper_script"
video_cmd=home+"video_helper_script"
cleanup_cmd=home+"cleanup_helper_script"
stream_file=home+"streams.dat"
key_a_file=home+"key_a.dat"
key_b_file=home+"key_b.dat"
key_c_file=home+"key_c.dat"
key_d_file=home+"key_d.dat"
is_key=""

def kill_everything():
    subprocess.Popen([cleanup_cmd])

def startstream(stream):
    global s
    global is_key

    (url,desc) = stream.split(',')
    msg="Playing stream "

    if (is_key != ""):
        msg=msg+"from "+is_key
        is_key=""
    else:
        msg=msg+"#"+str(s+1)
        
    msg=msg+": "+desc
    syslog.syslog(syslog.LOG_NOTICE, msg)

    subprocess.Popen([stream_cmd, url])

time.sleep(5)
syslog.syslog(syslog.LOG_NOTICE, "Hi there!")
syslog.syslog(syslog.LOG_NOTICE, "Waiting for network to be available.")


while True:
    nointernet=10
    try:
        socket.gethostbyname("youtube.com")
    except:
        time.sleep(1)
        nointernet=1

    if (nointernet == 10):
        break

syslog.syslog(syslog.LOG_NOTICE, "Network is up!")

with open(stream_file) as s:
    streams=s.readlines()

with open(key_a_file) as a:
    stream_a=a.readline()

with open(key_b_file) as b:
    stream_b=b.readline()

with open(key_c_file) as c:
    stream_c=c.readline()

with open(key_d_file) as d:
    stream_d=d.readline()


shuffle(streams)
numstreams=len(streams)

msg=str(numstreams)+" streams detected."
syslog.syslog(syslog.LOG_NOTICE, msg)

s = random.randint(1,numstreams)
s=s-1
startstream(streams[s])

@touchphat.on_release("Enter")
def back_one():
    kill_everything()

    global s
    s=s+1
    if s == numstreams:
        s = 0

    startstream(streams[s])

@touchphat.on_release("Back")
def forward_one():
    kill_everything()

    global s
    s=s-1
    if s == -1:
        s = (numstreams-1)

    startstream(streams[s])

@touchphat.on_release("A")
def key_a():
    global is_key
    kill_everything()

    is_key="hotey A"
    startstream(stream_a)

@touchphat.on_release("B")
def key_b():
    kill_everything()
    global is_key

    is_key="hotkey B"
    startstream(stream_b)

@touchphat.on_release("C")
def key_c():
    kill_everything()
    global is_key

    is_key="hotkey C"
    startstream(stream_c)

@touchphat.on_release("D")
def key_d():
    kill_everything()
    global is_key

    is_key="hotkey D"
    startstream(stream_d)


signal.pause()
